---
title: "Part 4: BASE-R Smoothing with Loess"
author: "David J Jackson"
date: "8/22/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
```

### LOESS (locally estimated scatterplot smoothing)
#### Source Code: http://r-statistics.co/Loess-Regression-With-R.html
#### Webpage Author: Selva Prabhakaran

```{r}
rm(list=ls())
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from ECDC")
df <- subset(df,Countries =="USA" & Cases >0 )
df$Reported <- as.Date(df$Reported)
names(df)
```
```{r}
db2 <- aggregate(Cases~Reported,data=df,FUN=sum)
db3 <- aggregate(Deaths~Reported,data=df,FUN=sum)
```
```{r}
plot(db2$Reported,db2$Cases,type="l",main="Plot of Cases by Date")
```
```{r}
plot(db3$Reported,db3$Deaths,type="l",main="Plot of Deaths by Date")
```

### Calculate and Plot Loess Fitted Curves

```{r}
db2$index <- 1:nrow(db2)
loess1 <- loess(db2$Cases~db2$index)
loess2 <- loess(db2$Cases~db2$index,span=0.25)
loess3 <- loess(db2$Cases~db2$index,span=0.50)
loess4 <- loess(db2$Cases~db2$index,span=0.75)

```
```{r}
db2$sm00 <- predict(loess1) 
db2$sm25 <- predict(loess2) 
db2$sm50 <- predict(loess3)
db2$sm75 <- predict(loess4)
```

#### Plot COVID9-19 Cases With Loess Smoothed Fit.

```{r}
plot(db2$Reported,db2$Cases, type="l", main="Cases: Loess(default) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db2$Reported,db2$sm00, col="red")

plot(db2$Reported,db2$Cases, type="l", main="Cases: Loess(0.25) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db2$Reported,db2$sm25, col="red")

plot(db2$Reported,db2$Cases, type="l", main="Cases: Loess(0.50) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db2$Reported,db2$sm50, col="red")

plot(db2$Reported,db2$Cases, type="l", main="Cases: Loess(0.75) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db2$Reported,db2$sm75, col="red")
```

#### Predict Lwoess for Deaths

```{r}
db3$index <- 1:nrow(db3)
loess1 <- loess(db3$Deaths~db3$index)
loess2 <- loess(db3$Deaths~db3$index,span=0.25)
loess3 <- loess(db3$Deaths~db3$index,span=0.50)
loess4 <- loess(db3$Deaths~db3$index,span=0.75)
```
```{r}
db3$sm00 <- predict(loess1) 
db3$sm25 <- predict(loess2) 
db3$sm50 <- predict(loess3)
db3$sm75 <- predict(loess4)
```

#### Plot COVID9-19 Cases With Loess Smoothed Fit.

```{r}
plot(db3$Reported,db3$Deaths, type="l", main="Deaths: Loess(default) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db3$Reported,db3$sm00, col="red")

plot(db3$Reported,db3$Deaths, type="l", main="Deaths: Loess(0.25) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db3$Reported,db3$sm25, col="red")

plot(db3$Reported,db3$Deaths, type="l", main="Deaths: Loess(0.50) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db3$Reported,db3$sm50, col="red")

plot(db3$Reported,db3$Deaths, type="l", main="Deaths: Loess(0.75) Smoothing and Prediction", xlab="Date", ylab="Total Cases")
lines(db3$Reported,db3$sm75, col="red")
```


