---
title: 'COVID-19: R Fitted Curve: Source'
author: "David J Jackson"
date: "8/9/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### In the interest of Full disclosure ...
#### There are packages that have moivng average function build in:

* Zoo, forecast,TTR and pracma.
* There are three ways of adding rolling means to you code:
* Embed the code directly
* Use the source command to read a *.R script
* Create and load a  package on Github


```{r}
source("../DATA/movavg.R")
```

```{r}

EUCOVID <- read.csv("../DATA/COVID-19-ECDCP-2020-08-10.csv")
EUCOVID$dateRep <- gsub("/","-",EUCOVID$dateRep)
EUCOVID$dateRep <- as.Date(EUCOVID$dateRep,format="%m-%d-%Y")
ES <- subset(EUCOVID,geoId =="US" & cases >0)
ES <- ES[c(1,5:8)]
```
```{r}
## 
## Calculate Moivng Average
##
ES$rollmean <- movingAverage(ES$cases,7,center=TRUE)
ES$rollmean2 <- movingAverage(ES$cases,28,center=TRUE)
```
```{r}
plot(ES$dateRep,ES$cases,type="l",main = "Comparing 7 Day Moving Average \n to 28 Day Moving Average",
     xlab="Date Reported",ylab="Mean Cases",col="red")
lines(ES$dateRep,ES$rollmean,col="blue")
 lines(ES$dateRep,ES$rollmean2,col="green")
legend("topleft",
       c("Daily Cases","7 Day Mov Av","28 Mov Avg."),
       col=c("red","blue","green"),
       lty = c(1, 1),
       cex = 0.8)
grid()
```
```{r}
plot(ES$dateRep,ES$rollmean,type="l",main = "Comparing 7 Day Moving Average \n to 28 Day Moving Average",
     xlab="Date Reported",ylab="Mean Cases",col="red")
lines(ES$dateRep,ES$rollmean2,col="blue")
legend("topleft",
       c("7 Day Mov Av","28 Mov Avg."),
       col=c("red","blue"),
       lty = c(1, 1),
       cex = 0.8)
grid()
```
